name: Update NAS RSS Feed

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feed
        run: python generate_rss.py

      - name: Commit and push RSS feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add nas_college_feed.xml
          git commit -m "Auto update NAS RSS feed" || echo "No changes"
          git push
